"""rules as rows, ruleset_version, review_decision

Revision ID: 0fccb21b7df2
Revises: e2f57fad7683
Create Date: 2026-06-19 15:53:01.922030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0fccb21b7df2'
down_revision: Union[str, Sequence[str], None] = 'e2f57fad7683'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_key', sa.String(length=80), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('jurisdiction', sa.String(length=16), nullable=False),
    # Reuse the existing `severity` enum (created in the initial migration) —
    # don't try to CREATE TYPE it again.
    sa.Column('severity', postgresql.ENUM('BLOCKER', 'WARNING', 'INFO', name='severity', create_type=False), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('applies_when', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('requirement', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('remediation', sa.Text(), nullable=False),
    sa.Column('source_citation', sa.Text(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_key', 'version', name='uq_rule_key_version')
    )
    op.create_table('ruleset_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('ruleset_version_rule',
    sa.Column('ruleset_version_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rule.id'], ),
    sa.ForeignKeyConstraint(['ruleset_version_id'], ['ruleset_version.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ruleset_version_id', 'rule_id')
    )
    op.create_table('review_decision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compliance_run_id', sa.Integer(), nullable=False),
    sa.Column('reviewer', sa.String(length=120), nullable=False),
    sa.Column('decision', sa.Enum('APPROVE', 'REJECT', 'OVERRIDE', name='reviewdecisiontype'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['compliance_run_id'], ['compliance_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('compliance_run', sa.Column('ruleset_version_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'fk_compliance_run_ruleset_version', 'compliance_run', 'ruleset_version',
        ['ruleset_version_id'], ['id'],
    )
    op.add_column('violation', sa.Column('rule_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_violation_rule', 'violation', 'rule', ['rule_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_violation_rule', 'violation', type_='foreignkey')
    op.drop_column('violation', 'rule_id')
    op.drop_constraint(
        'fk_compliance_run_ruleset_version', 'compliance_run', type_='foreignkey'
    )
    op.drop_column('compliance_run', 'ruleset_version_id')
    op.drop_table('review_decision')
    op.drop_table('ruleset_version_rule')
    op.drop_table('ruleset_version')
    op.drop_table('rule')
    # ### end Alembic commands ###
    # The reviewdecisiontype enum was created by this migration; drop it. The
    # severity enum is owned by the initial migration, so leave it.
    op.execute("DROP TYPE IF EXISTS reviewdecisiontype")
