"""initial schema: oem, dealership, vehicle, offer, ad_asset, compliance_run, violation

Revision ID: e2f57fad7683
Revises: 
Create Date: 2026-06-19 14:59:51.785613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2f57fad7683'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('brand_guidelines_ref', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('dealership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('dba_name', sa.String(length=160), nullable=True),
    sa.Column('oem_id', sa.Integer(), nullable=True),
    sa.Column('jurisdiction', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['oem_id'], ['oem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dealership_id', sa.Integer(), nullable=False),
    sa.Column('vin', sa.String(length=17), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=60), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('trim', sa.String(length=80), nullable=False),
    sa.Column('msrp', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('dealer_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.Column('condition', sa.Enum('NEW', 'USED', 'CERTIFIED', name='vehiclecondition'), nullable=False),
    sa.Column('stock_number', sa.String(length=40), nullable=False),
    sa.Column('body_style', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['dealership_id'], ['dealership.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vin')
    )
    op.create_table('ad_asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('GOOGLE', 'META', 'DISPLAY', 'EMAIL', name='channel'), nullable=False),
    sa.Column('format', sa.Enum('TEXT', 'IMAGE', 'HTML', name='assetformat'), nullable=False),
    sa.Column('generated_by', sa.String(length=40), nullable=False),
    sa.Column('copy_text', sa.Text(), nullable=True),
    sa.Column('image_s3_key', sa.String(length=256), nullable=True),
    sa.Column('generation_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('LEASE', 'FINANCE', 'CASH', 'REBATE', name='offertype'), nullable=False),
    sa.Column('apr', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('term_months', sa.Integer(), nullable=True),
    sa.Column('monthly_payment', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('down_payment', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('due_at_signing', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('residual', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('jurisdiction', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_asset_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PASS', 'FAIL', 'REQUIRES_REVIEW', name='verdict'), nullable=False),
    sa.Column('extracted_claims', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ad_asset_id'], ['ad_asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('violation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compliance_run_id', sa.Integer(), nullable=False),
    sa.Column('rule_key', sa.String(length=80), nullable=False),
    sa.Column('severity', sa.Enum('BLOCKER', 'WARNING', 'INFO', name='severity'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['compliance_run_id'], ['compliance_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('violation')
    op.drop_table('compliance_run')
    op.drop_table('offer')
    op.drop_table('ad_asset')
    op.drop_table('vehicle')
    op.drop_table('dealership')
    op.drop_table('oem')
    # ### end Alembic commands ###
